---

- name: containerd | Install containerd via binary
  when: containerd_install_method == "bin"
  block:
    - name: containerd | Install containerd bin
      ansible.builtin.include_tasks: "containerd_bin.yaml"
    - name: containerd | Install runc bin
      ansible.builtin.include_tasks: "runc_bin.yaml"

- name: containerd | Install containerd via apt
  when: containerd_install_method == "apt"
  block:
    - name: containerd | Install containerd apt
      ansible.builtin.include_tasks: "containerd_apt.yaml"

- name: containerd | Import CNI task
  ansible.builtin.include_tasks: "cni_bin.yaml"
