---

- name: Install dependencies
  ansible.builtin.package:
    name:
      - gnupg

- name: Create keyrings folder
  ansible.builtin.file:
    path: "{{ crio_apt_keyrings_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add cri-o apt repository key.
  ansible.builtin.get_url:
    url: "{{ crio_apt_gpg_url }}"
    dest: "{{ crio_apt_keyrings_dir }}/{{ crio_apt_keyrings_file }}"
    owner: root
    group: root
    mode: '0644'

- name: Add cri-o repository
  ansible.builtin.deb822_repository:
    name: cri-o
    types: deb
    uris: "{{ crio_apt_source }}"
    suites: release
    components: main
    architectures: "{{ crio_arch }}"
    signed_by: "{{ crio_apt_keyrings_dir }}/{{ crio_apt_keyrings_file }}"
    state: present

- name: Install cri-o
  ansible.builtin.package:
    name:
      - cri-o
    update_cache: true
    state: present
