---

- name: gvisor | Install dependencies
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg

- name: gvisor | Create keyrings folder
  ansible.builtin.file:
    path: "{{ gvisor_apt_keyrings_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: gvisor | Add gVisor's official GPG key
  ansible.builtin.get_url:
    url: "{{ gvisor_apt_gpg_url }}"
    dest: "{{ gvisor_apt_keyrings_dir }}/{{ gvisor_apt_keyrings_file }}"
    owner: root
    group: root
    mode: '0644'

- name: gvisor | Add gVisor repository
  ansible.builtin.deb822_repository:
    name: gvisor
    types: deb
    uris: "{{ gvisor_apt_source }}"
    suites: release
    components: main
    architectures: "{{ gvisor_arch }}"
    signed_by: "{{ gvisor_apt_keyrings_dir }}/{{ gvisor_apt_keyrings_file }}"
    state: present

- name: gvisor | Install gVisor
  ansible.builtin.package:
    name:
      - runsc={{ gvisor_apt_version }}
    update_cache: true
    state: present
