---

- name: gvisor | Check if runsc is installed
  ansible.builtin.stat:
    path: "{{ gvisor_bin_dir }}/runsc"
  register: gvisor_file
  ignore_errors: true

- name: gvisor | Get current gvisor version
  ansible.builtin.command: "{{ gvisor_bin_dir }}/runsc --version"
  register: gvisor_current_version
  when: gvisor_file.stat.exists
  changed_when: false

- name: gvisor | Install runsc
  when: |
    not gvisor_file.stat.exists
    or gvisor_version not in gvisor_current_version.stdout
  block:
    - name: "gvisor | Download gVisor archive"
      ansible.builtin.get_url:
        url: "{{ gvisor_bin_url }}/gvisor.tar.zstd"
        checksum: "sha512:{{ gvisor_bin_url }}/gvisor.tar.zstd.sha512"
        dest: "/tmp/gvisor.tar.zstd"
        mode: '0644'
        owner: root
        group: root
    - name: "gvisor | Extract gVisor archive"
      ansible.builtin.unarchive:
        src: "/tmp/gvisor.tar.zstd"
        dest: "{{ gvisor_bin_dir }}"
        remote_src: true
        owner: root
        group: root
        mode: '0755'
        extra_opts:
          - "--zstd"
    - name: "gvisor | Remove downloaded archive"
      ansible.builtin.file:
        path: "/tmp/gvisor.tar.zstd"
        state: absent
